import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
user_app_path = rtconfig.USER_APP_DIR
comp_packages_path = rtconfig.COMP_PACKAGES_DIR

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

# add user app search
if os.path.exists(os.path.join(user_app_path, 'SConscript')):
	group = group + SConscript(os.path.join(user_app_path, 'SConscript'), 
        variant_dir=rtconfig.BUILD_OUT_DIR + '/user_app/', duplicate=0)

# add component rtt packages src search
if os.path.exists(os.path.join(comp_packages_path, 'SConscript')):
	group = group + SConscript(os.path.join(comp_packages_path, 'SConscript'), 
        variant_dir=rtconfig.BUILD_OUT_DIR + '/rtt_packages/', duplicate=0)

Return('group')
