// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_Bg;
void ui_event_BtnSWVersion(lv_event_t * e);
extern lv_obj_t * ui_BtnSWVersion;
extern lv_obj_t * ui_Label1;
void ui_event_BtnBootVersion(lv_event_t * e);
extern lv_obj_t * ui_BtnBootVersion;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_TabViewBootVersion;
void ui_event_uiBtnSWCode(lv_event_t * e);
extern lv_obj_t * ui_uiBtnSWCode;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TabViewSWCode;
void ui_event_BtnReqDtc(lv_event_t * e);
extern lv_obj_t * ui_BtnReqDtc;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TabViewdtc;
void ui_event_BtnClearDtc(lv_event_t * e);
extern lv_obj_t * ui_BtnClearDtc;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_LabelTitle;
void ui_event_BtnUpLoad(lv_event_t * e);
extern lv_obj_t * ui_BtnUpLoad;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TabViewSWVersion;
extern lv_obj_t * ui_LabelSWVersion;
extern lv_obj_t * ui_LabelBootVersion;
extern lv_obj_t * ui_LabelSWCode;
extern lv_obj_t * ui_Labeldtc;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBright;
extern lv_obj_t * ui_LabelHigh;
void ui_event_SliderHigh(lv_event_t * e);
extern lv_obj_t * ui_SliderHigh;
void ui_event_DropdownTestPic(lv_event_t * e);
extern lv_obj_t * ui_DropdownTestPic;
void ui_event_BtnConnNet(lv_event_t * e);
extern lv_obj_t * ui_BtnConnNet;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg_img_png);    // assets\bg_img.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
