// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

typedef struct __UI_Resp_Can_Data
{
    uint32_t id;
    uint16_t len;
    uint8_t *data;

}ui_Resp_Can_Data;

extern int can_port_req_uds_cmd(uint16_t id, uint16_t len, uint8_t* p_cmd, void* userdata);
extern uint8_t api_tcpclient_connect();
extern void api_tcpclient_send(uint8_t type, const char* p_data);


uint8_t respGetswVer[16];
uint8_t respGetbootVer[16];
uint8_t respGetswCode[32];
uint8_t respGetDtcCode[64];

void BtnSWVersion_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnSWVersion_event_handler \n");
    lv_label_set_text(ui_LabelSWVersion, "v1.00.10");
}

void BtnBootVersion_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnBootVersion_event_handler \n");
    lv_label_set_text(ui_LabelBootVersion, "v1.1.0");
}

void BtnSWCode_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnSWCode_event_handler \n");
    lv_label_set_text(ui_LabelSWCode, "483300118899000000");
}

void BtnReqDtc_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnReqDtc_event_handler \n");
    lv_label_set_text(ui_Labeldtc, "456\n765\n987\n4833001");
}

void BtnClearDtc_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnClearDtc_event_handler \n");
}

// -------------------------------------------------------

void Event_Brightness_Handler(lv_event_t * e)
{
	// Your code here
    rt_kprintf("\r Event_Brightness_Handler \n");
    lv_obj_t * target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);
    rt_kprintf("\r %d\n", value);
}

void Event_TestPic_Handler(lv_event_t * e)
{
	// Your code here
    char buf[20];
    rt_kprintf("\r Event_TestPic_Handler \n");
    lv_obj_t * target = lv_event_get_target(e);
    lv_dropdown_get_selected_str(target, &buf, 20);
    rt_kprintf("\r %s\n", buf);

    uint8_t index_pic = lv_dropdown_get_selected(target);
    rt_kprintf("index_pic: %d\n", index_pic);
}

void Event_High_Handler(lv_event_t * e)
{
	// Your code here
    rt_kprintf("\r Event_High_Handler \n");
    lv_obj_t * target = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(target);
    rt_kprintf("\r %d\n", value);
}

// ----------------------------------------------------------------------

void BtnUpLoad_event_handler(lv_event_t * e)
{
    // Your code here
    rt_kprintf("\r BtnUpLoad_event_handler \n");

    uint8_t bufSend[1024];
    rt_memset(bufSend, 0x00, sizeof(bufSend));
    rt_sprintf(bufSend, " SW-Version:%s;\n Boot-Version:%s;\n SW-Code:%s;\n Dtc:%s;\n",respGetswVer, respGetbootVer, respGetswCode, respGetDtcCode);
    rt_kprintf("\r [long] tcp upload :%s\n", bufSend);
}

void BtnConnNet_event_handler(lv_event_t * e)
{
	// Your code here
    rt_kprintf("\r BtnConnNet_event_handler \n");
    char* buf = lv_label_get_text(ui_Label7);
    char bufSend[] = "";
    rt_kprintf("\r %s\n", *buf);

    if (strcmp(buf, "connect") == 0)
    {
        uint8_t ret = 1;// api_tcpclient_connect();
        if (ret == 1)
        {
            rt_kprintf("\r [long] tcp connect success ! \n");
            lv_label_set_text(ui_Label7, "disconn");
        }
        else {
            rt_kprintf("\r [long] tcp connect fail ! \n");
        }
    }
    else
    {
        lv_label_set_text(ui_Label7, "connect");
        //api_tcpclient_send(0xFF, bufSend);
    }

}

