/* generated configuration header file - do not edit */
#ifndef BSP_PIN_CFG_H_
#define BSP_PIN_CFG_H_
#include "r_ioport.h"
#define ARDUINO_AN00 (BSP_IO_PORT_00_PIN_00)
#define ARDUINO_A1 (BSP_IO_PORT_00_PIN_01)
#define ARDUINO_A2 (BSP_IO_PORT_00_PIN_02)
#define CTSU_TS1 (BSP_IO_PORT_00_PIN_12)
#define CTSU_TS2 (BSP_IO_PORT_00_PIN_13)
#define CTSU_TS3 (BSP_IO_PORT_00_PIN_15)
#define PMODA_MISOA_RXD0 (BSP_IO_PORT_01_PIN_00)
#define PMODA_MOSIA_TXD0 (BSP_IO_PORT_01_PIN_01)
#define PMODA_RSPCKA_SCK0 (BSP_IO_PORT_01_PIN_02)
#define PMODA_SSLA0_CTS0 (BSP_IO_PORT_01_PIN_03)
#define ARDUINO_GPIO_IRQ01 (BSP_IO_PORT_01_PIN_04)
#define DEBUG_SWDIO_TMS (BSP_IO_PORT_01_PIN_08)
#define DEBUG_TDO (BSP_IO_PORT_01_PIN_09)
#define DEBUG_TDI (BSP_IO_PORT_01_PIN_10)
#define ARDUINO_GPIO_GTIOC6 (BSP_IO_PORT_01_PIN_11)
#define ARDUINO_GPIO_CLK (BSP_IO_PORT_01_PIN_12)
#define MD (BSP_IO_PORT_02_PIN_01)
#define ARDUINO_RX_MIKROBUS_RX (BSP_IO_PORT_02_PIN_06)
#define ARDUINO_RST (BSP_IO_PORT_02_PIN_07)
#define PMODA_IO1 (BSP_IO_PORT_02_PIN_08)
#define EXTAL (BSP_IO_PORT_02_PIN_12)
#define XTAL (BSP_IO_PORT_02_PIN_13)
#define XCOUT (BSP_IO_PORT_02_PIN_14)
#define XCIN (BSP_IO_PORT_02_PIN_15)
#define DEBUG_SWDCLK_TCK (BSP_IO_PORT_03_PIN_00)
#define GROVE_SCL (BSP_IO_PORT_03_PIN_01)
#define GROVE_SDA (BSP_IO_PORT_03_PIN_02)
#define PMODB_SCK1 (BSP_IO_PORT_04_PIN_00)
#define PMODB_MOSI_TXD1 (BSP_IO_PORT_04_PIN_01)
#define ARDUINO_SDA (BSP_IO_PORT_04_PIN_07)
#define ARDUINO_SCL (BSP_IO_PORT_04_PIN_08)
#define PMODB_IRQ06 (BSP_IO_PORT_04_PIN_09)
#define ARDUINO_GPIO_GTIOC5 (BSP_IO_PORT_05_PIN_00)
#define USER_LED3 (BSP_IO_PORT_09_PIN_13)
#define USER_LED2 (BSP_IO_PORT_09_PIN_14)
#define USER_LED1 (BSP_IO_PORT_09_PIN_15)
extern const ioport_cfg_t g_bsp_pin_cfg; /* RA2L1 CPK */

void BSP_PinConfigSecurityInit();
#endif /* BSP_PIN_CFG_H_ */
