# for module compiling
import os
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = []
list = os.listdir(cwd)

if rtconfig.PLATFORM in ['iccarm']:
    print("\nThe current project does not support IAR build\n")
    Return('group')
elif rtconfig.PLATFORM in ['gcc', 'armclang']:
    if GetOption('target') != 'mdk5':
        CPPPATH = [cwd + './src']
        src = Glob('./src/*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)
print(group)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
    	print(os.path.join(path, 'SConscript'))
    	print(d)
    	print(rtconfig.BUILD_OUT_DIR + '/' + d)
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
