// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
lv_obj_t * ui_Screen;
lv_obj_t * ui_Bg;
void ui_event_BtnSWVersion(lv_event_t * e);
lv_obj_t * ui_BtnSWVersion;
lv_obj_t * ui_Label1;
void ui_event_BtnBootVersion(lv_event_t * e);
lv_obj_t * ui_BtnBootVersion;
lv_obj_t * ui_Label2;
lv_obj_t * ui_TabViewBootVersion;
void ui_event_uiBtnSWCode(lv_event_t * e);
lv_obj_t * ui_uiBtnSWCode;
lv_obj_t * ui_Label3;
lv_obj_t * ui_TabViewSWCode;
void ui_event_BtnReqDtc(lv_event_t * e);
lv_obj_t * ui_BtnReqDtc;
lv_obj_t * ui_Label4;
lv_obj_t * ui_TabViewdtc;
void ui_event_BtnClearDtc(lv_event_t * e);
lv_obj_t * ui_BtnClearDtc;
lv_obj_t * ui_Label5;
lv_obj_t * ui_LabelTitle;
void ui_event_BtnUpLoad(lv_event_t * e);
lv_obj_t * ui_BtnUpLoad;
lv_obj_t * ui_Label6;
lv_obj_t * ui_TabViewSWVersion;
lv_obj_t * ui_LabelSWVersion;
lv_obj_t * ui_LabelBootVersion;
lv_obj_t * ui_LabelSWCode;
lv_obj_t * ui_Labeldtc;
void ui_event_SliderBrightness(lv_event_t * e);
lv_obj_t * ui_SliderBrightness;
lv_obj_t * ui_LabelBright;
lv_obj_t * ui_LabelHigh;
void ui_event_SliderHigh(lv_event_t * e);
lv_obj_t * ui_SliderHigh;
void ui_event_DropdownTestPic(lv_event_t * e);
lv_obj_t * ui_DropdownTestPic;
void ui_event_BtnConnNet(lv_event_t * e);
lv_obj_t * ui_BtnConnNet;
lv_obj_t * ui_Label7;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BtnSWVersion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnSWVersion_event_handler(e);
    }
}
void ui_event_BtnBootVersion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnBootVersion_event_handler(e);
    }
}
void ui_event_uiBtnSWCode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnSWCode_event_handler(e);
    }
}
void ui_event_BtnReqDtc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnReqDtc_event_handler(e);
    }
}
void ui_event_BtnClearDtc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnClearDtc_event_handler(e);
    }
}
void ui_event_BtnUpLoad(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnUpLoad_event_handler(e);
    }
}
void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Event_Brightness_Handler(e);
    }
}
void ui_event_SliderHigh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Event_High_Handler(e);
    }
}
void ui_event_DropdownTestPic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Event_TestPic_Handler(e);
    }
}
void ui_event_BtnConnNet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnConnNet_event_handler(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen);
}
