// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BtnSWVersion_event_handler(lv_event_t * e);
void BtnBootVersion_event_handler(lv_event_t * e);
void BtnSWCode_event_handler(lv_event_t * e);
void BtnReqDtc_event_handler(lv_event_t * e);
void BtnClearDtc_event_handler(lv_event_t * e);
void BtnUpLoad_event_handler(lv_event_t * e);
void Event_Brightness_Handler(lv_event_t * e);
void Event_High_Handler(lv_event_t * e);
void Event_TestPic_Handler(lv_event_t * e);
void BtnConnNet_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
