// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void welcomescreen_event_handler(lv_event_t * e);
void Btnyuwenbaozang_event_handler(lv_event_t * e);
void Btnshuxueyunsuan_event_handler(lv_event_t * e);
void Btnyingyuqimeng_event_handler(lv_event_t * e);
void Btnzhinengai_event_handler(lv_event_t * e);
void Btnquweidonghua_event_handler(lv_event_t * e);
void Btnxitongshezhi_event_handler(lv_event_t * e);
void Btnxitongshengji_event_handler(lv_event_t * e);
void Btnwifishezhi_event_handler(lv_event_t * e);
void keyenter_event_handler(lv_event_t * e);
void keyready_event_handler(lv_event_t * e);
void keycancel_event_hadnler(lv_event_t * e);
void scanwifilist_event_handler(lv_event_t * e);
void switchnopasswordmode_event_handler(lv_event_t * e);
void switchpasswordmode_event_handler(lv_event_t * e);
void Screenquweidonghualeft_event_handler(lv_event_t * e);
void Screenquweidonghuaright_event_handler(lv_event_t * e);
void Btnchangchangyingyu_event_handler(lv_event_t * e);
void Btnxiaozhupeiqi_event_handler(lv_event_t * e);
void Screenzhinengaileft_event_handler(lv_event_t * e);
void Screenzhinengairight_event_handler(lv_event_t * e);
void Btntonghuagushi_event_handler(lv_event_t * e);
void Btnzhishibaike_event_handler(lv_event_t * e);
void Screenyuwenbaozangleft_event_handler(lv_event_t * e);
void Screenyuwenbaozangright_event_handler(lv_event_t * e);
void Btnguoxuetangshi_event_handler(lv_event_t * e);
void Btnsanzijing_event_handler(lv_event_t * e);
void Btnjiafayunsuan_event_handler(lv_event_t * e);
void Btnjianfayunsuan_event_handler(lv_event_t * e);
void Btnfanhuizhuye4_event_handler(lv_event_t * e);
void Btnchongxinchuti_event_handler(lv_event_t * e);
void Btnchakandaan_event_handler(lv_event_t * e);
void Dropdownmaxnum_event_handler(lv_event_t * e);
void Screenyingyuqimengleft_event_handler(lv_event_t * e);
void Screenyingyuqimengright_event_handler(lv_event_t * e);
void Btnrenshizimu_event_handler(lv_event_t * e);
void Btnquweidanci_event_handler(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
