// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_screen_init(void)
{
ui_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bg = lv_img_create(ui_Screen);
lv_img_set_src(ui_Bg, &ui_img_bg_img_png);
lv_obj_set_width( ui_Bg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Bg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnSWVersion = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnSWVersion, 100);
lv_obj_set_height( ui_BtnSWVersion, 26);
lv_obj_set_x( ui_BtnSWVersion, -175 );
lv_obj_set_y( ui_BtnSWVersion, -80 );
lv_obj_set_align( ui_BtnSWVersion, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnSWVersion, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnSWVersion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_BtnSWVersion);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -1 );
lv_obj_set_y( ui_Label1, -1 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Version");

ui_BtnBootVersion = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnBootVersion, 100);
lv_obj_set_height( ui_BtnBootVersion, 26);
lv_obj_set_x( ui_BtnBootVersion, -175 );
lv_obj_set_y( ui_BtnBootVersion, -40 );
lv_obj_set_align( ui_BtnBootVersion, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnBootVersion, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnBootVersion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_BtnBootVersion);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -1 );
lv_obj_set_y( ui_Label2, -1 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Boot");

ui_TabViewBootVersion = lv_tabview_create(ui_Screen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViewBootVersion, 100);
lv_obj_set_height( ui_TabViewBootVersion, 26);
lv_obj_set_x( ui_TabViewBootVersion, -55 );
lv_obj_set_y( ui_TabViewBootVersion, -40 );
lv_obj_set_align( ui_TabViewBootVersion, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViewBootVersion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_uiBtnSWCode = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_uiBtnSWCode, 100);
lv_obj_set_height( ui_uiBtnSWCode, 26);
lv_obj_set_x( ui_uiBtnSWCode, -175 );
lv_obj_set_y( ui_uiBtnSWCode, 0 );
lv_obj_set_align( ui_uiBtnSWCode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_uiBtnSWCode, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_uiBtnSWCode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_uiBtnSWCode);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -1 );
lv_obj_set_y( ui_Label3, -1 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Code");

ui_TabViewSWCode = lv_tabview_create(ui_Screen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViewSWCode, 100);
lv_obj_set_height( ui_TabViewSWCode, 26);
lv_obj_set_x( ui_TabViewSWCode, -55 );
lv_obj_set_y( ui_TabViewSWCode, 0 );
lv_obj_set_align( ui_TabViewSWCode, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViewSWCode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_BtnReqDtc = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnReqDtc, 65);
lv_obj_set_height( ui_BtnReqDtc, 26);
lv_obj_set_x( ui_BtnReqDtc, 78 );
lv_obj_set_y( ui_BtnReqDtc, -80 );
lv_obj_set_align( ui_BtnReqDtc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnReqDtc, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnReqDtc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_BtnReqDtc);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -1 );
lv_obj_set_y( ui_Label4, -1 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"dtc");

ui_TabViewdtc = lv_tabview_create(ui_Screen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViewdtc, 166);
lv_obj_set_height( ui_TabViewdtc, 79);
lv_obj_set_x( ui_TabViewdtc, 125 );
lv_obj_set_y( ui_TabViewdtc, -19 );
lv_obj_set_align( ui_TabViewdtc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViewdtc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_BtnClearDtc = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnClearDtc, 65);
lv_obj_set_height( ui_BtnClearDtc, 26);
lv_obj_set_x( ui_BtnClearDtc, 171 );
lv_obj_set_y( ui_BtnClearDtc, -80 );
lv_obj_set_align( ui_BtnClearDtc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnClearDtc, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnClearDtc, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_BtnClearDtc);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -1 );
lv_obj_set_y( ui_Label5, -1 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"clear");

ui_LabelTitle = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTitle, -2 );
lv_obj_set_y( ui_LabelTitle, -121 );
lv_obj_set_align( ui_LabelTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTitle,"Recan LGVL Demo");
lv_obj_set_style_text_color(ui_LabelTitle, lv_color_hex(0xFF1480), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnUpLoad = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnUpLoad, 74);
lv_obj_set_height( ui_BtnUpLoad, 26);
lv_obj_set_x( ui_BtnUpLoad, 170 );
lv_obj_set_y( ui_BtnUpLoad, 109 );
lv_obj_set_align( ui_BtnUpLoad, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnUpLoad, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnUpLoad, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_BtnUpLoad);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -1 );
lv_obj_set_y( ui_Label6, -1 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"upload");

ui_TabViewSWVersion = lv_tabview_create(ui_Screen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViewSWVersion, 100);
lv_obj_set_height( ui_TabViewSWVersion, 26);
lv_obj_set_x( ui_TabViewSWVersion, -55 );
lv_obj_set_y( ui_TabViewSWVersion, -80 );
lv_obj_set_align( ui_TabViewSWVersion, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViewSWVersion, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_LabelSWVersion = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelSWVersion, 96);
lv_obj_set_height( ui_LabelSWVersion, 18);
lv_obj_set_x( ui_LabelSWVersion, -55 );
lv_obj_set_y( ui_LabelSWVersion, -80 );
lv_obj_set_align( ui_LabelSWVersion, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelSWVersion,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LabelSWVersion,"0.00.00");
lv_obj_set_style_text_color(ui_LabelSWVersion, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSWVersion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBootVersion = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelBootVersion, 96);
lv_obj_set_height( ui_LabelBootVersion, 18);
lv_obj_set_x( ui_LabelBootVersion, -55 );
lv_obj_set_y( ui_LabelBootVersion, -40 );
lv_obj_set_align( ui_LabelBootVersion, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelBootVersion,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LabelBootVersion,"0.00.00");
lv_obj_set_style_text_color(ui_LabelBootVersion, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBootVersion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSWCode = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelSWCode, 96);
lv_obj_set_height( ui_LabelSWCode, 18);
lv_obj_set_x( ui_LabelSWCode, -55 );
lv_obj_set_y( ui_LabelSWCode, 0 );
lv_obj_set_align( ui_LabelSWCode, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LabelSWCode,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_LabelSWCode,"hello world");
lv_obj_set_style_text_color(ui_LabelSWCode, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSWCode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Labeldtc = lv_label_create(ui_Screen);
lv_obj_set_width( ui_Labeldtc, 162);
lv_obj_set_height( ui_Labeldtc, 76);
lv_obj_set_x( ui_Labeldtc, 125 );
lv_obj_set_y( ui_Labeldtc, -19 );
lv_obj_set_align( ui_Labeldtc, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Labeldtc,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Labeldtc,"");
lv_obj_set_style_text_color(ui_Labeldtc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Labeldtc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderBrightness = lv_slider_create(ui_Screen);
lv_slider_set_value( ui_SliderBrightness, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBrightness, 150);
lv_obj_set_height( ui_SliderBrightness, 10);
lv_obj_set_x( ui_SliderBrightness, -60 );
lv_obj_set_y( ui_SliderBrightness, 40 );
lv_obj_set_align( ui_SliderBrightness, LV_ALIGN_CENTER );


ui_LabelBright = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelBright, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBright, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBright, -180 );
lv_obj_set_y( ui_LabelBright, 40 );
lv_obj_set_align( ui_LabelBright, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBright,"Brightness");
lv_obj_set_style_text_color(ui_LabelBright, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBright, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHigh = lv_label_create(ui_Screen);
lv_obj_set_width( ui_LabelHigh, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHigh, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHigh, -200 );
lv_obj_set_y( ui_LabelHigh, 80 );
lv_obj_set_align( ui_LabelHigh, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHigh,"Hight");
lv_obj_set_style_text_color(ui_LabelHigh, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHigh, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderHigh = lv_slider_create(ui_Screen);
lv_slider_set_value( ui_SliderHigh, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderHigh)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderHigh, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderHigh, 150);
lv_obj_set_height( ui_SliderHigh, 10);
lv_obj_set_x( ui_SliderHigh, -60 );
lv_obj_set_y( ui_SliderHigh, 80 );
lv_obj_set_align( ui_SliderHigh, LV_ALIGN_CENTER );


ui_DropdownTestPic = lv_dropdown_create(ui_Screen);
lv_dropdown_set_options( ui_DropdownTestPic, "Pic_Off\nPic_001\nPic_002\nPic_003\nPic_004\nPic_005\nPic_006\nPic_007\nPic_008\nPic_009\nPic_010\nPic_011\nPic_012\nPic_013\nPic_014\nPic_015\nPic_016\nPic_017\nPic_018\nPic_019\nPic_020\nPic_021\nPic_022\nPic_023\nPic_024\nPic_025\nPic_026\nPic_027\nPic_028\nPic_029\nPic_030" );
lv_obj_set_width( ui_DropdownTestPic, 161);
lv_obj_set_height( ui_DropdownTestPic, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropdownTestPic, 125 );
lv_obj_set_y( ui_DropdownTestPic, 57 );
lv_obj_set_align( ui_DropdownTestPic, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownTestPic, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_BtnConnNet = lv_btn_create(ui_Screen);
lv_obj_set_width( ui_BtnConnNet, 74);
lv_obj_set_height( ui_BtnConnNet, 26);
lv_obj_set_x( ui_BtnConnNet, 86 );
lv_obj_set_y( ui_BtnConnNet, 109 );
lv_obj_set_align( ui_BtnConnNet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BtnConnNet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnConnNet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_BtnConnNet);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, -1 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"connect");

lv_obj_add_event_cb(ui_BtnSWVersion, ui_event_BtnSWVersion, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnBootVersion, ui_event_BtnBootVersion, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uiBtnSWCode, ui_event_uiBtnSWCode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnReqDtc, ui_event_BtnReqDtc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnClearDtc, ui_event_BtnClearDtc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnUpLoad, ui_event_BtnUpLoad, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderHigh, ui_event_SliderHigh, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DropdownTestPic, ui_event_DropdownTestPic, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BtnConnNet, ui_event_BtnConnNet, LV_EVENT_ALL, NULL);

}
