// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void BtnSWVersion_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnBootVersion_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnSWCode_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnReqDtc_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnClearDtc_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnUpLoad_event_handler(lv_event_t * e)
{
	// Your code here
}

void Event_Brightness_Handler(lv_event_t * e)
{
	// Your code here
}

void Event_High_Handler(lv_event_t * e)
{
	// Your code here
}

void Event_TestPic_Handler(lv_event_t * e)
{
	// Your code here
}

void BtnConnNet_event_handler(lv_event_t * e)
{
	// Your code here
}
