// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_welcomescreen
void ui_welcomescreen_screen_init(void);
void ui_event_welcomescreen( lv_event_t * e);
lv_obj_t *ui_welcomescreen;
lv_obj_t *ui_Bg7;


// SCREEN: ui_mainscreen
void ui_mainscreen_screen_init(void);
lv_obj_t *ui_mainscreen;
lv_obj_t *ui_Bg;
lv_obj_t *ui_LabelTitle;
void ui_event_Btnyuwenbaozang( lv_event_t * e);
lv_obj_t *ui_Btnyuwenbaozang;
lv_obj_t *ui_Label1;
void ui_event_Btnshuxueyunsuan( lv_event_t * e);
lv_obj_t *ui_Btnshuxueyunsuan;
lv_obj_t *ui_Label4;
void ui_event_Btnyingyuqimeng( lv_event_t * e);
lv_obj_t *ui_Btnyingyuqimeng;
lv_obj_t *ui_Label5;
void ui_event_Btnzhinengai( lv_event_t * e);
lv_obj_t *ui_Btnzhinengai;
lv_obj_t *ui_Label2;
void ui_event_Btnquweidonghua( lv_event_t * e);
lv_obj_t *ui_Btnquweidonghua;
lv_obj_t *ui_Label3;
void ui_event_Btnxitongshezhi( lv_event_t * e);
lv_obj_t *ui_Btnxitongshezhi;
lv_obj_t *ui_Label6;


// SCREEN: ui_xitongshezhi
void ui_xitongshezhi_screen_init(void);
lv_obj_t *ui_xitongshezhi;
lv_obj_t *ui_Bg1;
lv_obj_t *ui_LabelTitle1;
void ui_event_Btnxitongshengji( lv_event_t * e);
lv_obj_t *ui_Btnxitongshengji;
lv_obj_t *ui_Label7;
void ui_event_Btnwifishezhi( lv_event_t * e);
lv_obj_t *ui_Btnwifishezhi;
lv_obj_t *ui_Label10;
void ui_event_Btnfanhuizhuye( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye;
lv_obj_t *ui_Label11;
lv_obj_t *ui_TabViewxitongshezhi;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Dropdownwifilist;
void ui_event_Keyboardwifipasswordinput( lv_event_t * e);
lv_obj_t *ui_Keyboardwifipasswordinput;
lv_obj_t *ui_textareainputpasswod;
void ui_event_Label31( lv_event_t * e);
lv_obj_t *ui_Label31;
lv_obj_t *ui_Label32;
void ui_event_Switchpasswordmode( lv_event_t * e);
lv_obj_t *ui_Switchpasswordmode;


// SCREEN: ui_quweidonghua
void ui_quweidonghua_screen_init(void);
lv_obj_t *ui_quweidonghua;
lv_obj_t *ui_Bg2;
lv_obj_t *ui_LabelTitle2;
void ui_event_Btnchangchangyingyu( lv_event_t * e);
lv_obj_t *ui_Btnchangchangyingyu;
lv_obj_t *ui_Label8;
void ui_event_Btnxiaozhupeiqi( lv_event_t * e);
lv_obj_t *ui_Btnxiaozhupeiqi;
lv_obj_t *ui_Label9;
void ui_event_Btnfanhuizhuye1( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye1;
lv_obj_t *ui_Label12;
lv_obj_t *ui_TabViewquweidonghua;


// SCREEN: ui_zhinengai
void ui_zhinengai_screen_init(void);
lv_obj_t *ui_zhinengai;
lv_obj_t *ui_Bg3;
lv_obj_t *ui_LabelTitle3;
void ui_event_Btntonghuagushi( lv_event_t * e);
lv_obj_t *ui_Btntonghuagushi;
lv_obj_t *ui_Label13;
void ui_event_Btnzhishikepu( lv_event_t * e);
lv_obj_t *ui_Btnzhishikepu;
lv_obj_t *ui_Label14;
void ui_event_Btnfanhuizhuye2( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye2;
lv_obj_t *ui_Label15;
lv_obj_t *ui_TabViezhinengai;


// SCREEN: ui_yuwenbaozang
void ui_yuwenbaozang_screen_init(void);
lv_obj_t *ui_yuwenbaozang;
lv_obj_t *ui_Bg4;
lv_obj_t *ui_LabelTitle4;
void ui_event_Btnguoxuetangshi( lv_event_t * e);
lv_obj_t *ui_Btnguoxuetangshi;
lv_obj_t *ui_Label16;
void ui_event_Btnsanzijing( lv_event_t * e);
lv_obj_t *ui_Btnsanzijing;
lv_obj_t *ui_Label17;
void ui_event_Btnfanhuizhuye3( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye3;
lv_obj_t *ui_Label18;
void ui_event_Imageyuwenbaozang( lv_event_t * e);
lv_obj_t *ui_Imageyuwenbaozang;


// SCREEN: ui_shuxueyunsuan
void ui_shuxueyunsuan_screen_init(void);
lv_obj_t *ui_shuxueyunsuan;
lv_obj_t *ui_Bg5;
lv_obj_t *ui_LabelTitle5;
void ui_event_Btnjiafayunsuan( lv_event_t * e);
lv_obj_t *ui_Btnjiafayunsuan;
lv_obj_t *ui_Label19;
void ui_event_Btnjianfayunsuan( lv_event_t * e);
lv_obj_t *ui_Btnjianfayunsuan;
lv_obj_t *ui_Label20;
void ui_event_Btnfanhuizhuye4( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye4;
lv_obj_t *ui_Label21;
lv_obj_t *ui_TabViezhinengai2;
void ui_event_Btnchongxinchuti( lv_event_t * e);
lv_obj_t *ui_Btnchongxinchuti;
lv_obj_t *ui_Label25;
void ui_event_Btnchakandaan( lv_event_t * e);
lv_obj_t *ui_Btnchakandaan;
lv_obj_t *ui_Label26;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Label28;
void ui_event_Dropdownmaxnum( lv_event_t * e);
lv_obj_t *ui_Dropdownmaxnum;


// SCREEN: ui_yingyuqimeng
void ui_yingyuqimeng_screen_init(void);
lv_obj_t *ui_yingyuqimeng;
lv_obj_t *ui_Bg6;
lv_obj_t *ui_LabelTitle6;
void ui_event_Btnrenshizimu( lv_event_t * e);
lv_obj_t *ui_Btnrenshizimu;
lv_obj_t *ui_Label22;
void ui_event_Btnquweidanci( lv_event_t * e);
lv_obj_t *ui_Btnquweidanci;
lv_obj_t *ui_Label23;
void ui_event_Btnfanhuizhuye5( lv_event_t * e);
lv_obj_t *ui_Btnfanhuizhuye5;
lv_obj_t *ui_Label24;
lv_obj_t *ui_TabViezhinengai3;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_welcomescreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      welcomescreen_event_handler( e );
}
}
void ui_event_Btnyuwenbaozang( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_yuwenbaozang, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yuwenbaozang_screen_init);
      Btnyuwenbaozang_event_handler( e );
}
}
void ui_event_Btnshuxueyunsuan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_shuxueyunsuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_shuxueyunsuan_screen_init);
      Btnshuxueyunsuan_event_handler( e );
}
}
void ui_event_Btnyingyuqimeng( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_yingyuqimeng, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yingyuqimeng_screen_init);
      Btnyingyuqimeng_event_handler( e );
}
}
void ui_event_Btnzhinengai( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_zhinengai, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_zhinengai_screen_init);
      Btnzhinengai_event_handler( e );
}
}
void ui_event_Btnquweidonghua( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_quweidonghua, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_quweidonghua_screen_init);
      Btnquweidonghua_event_handler( e );
}
}
void ui_event_Btnxitongshezhi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_xitongshezhi, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_xitongshezhi_screen_init);
      Btnxitongshezhi_event_handler( e );
}
}
void ui_event_Btnxitongshengji( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnxitongshengji_event_handler( e );
}
}
void ui_event_Btnwifishezhi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnwifishezhi_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
}
}
void ui_event_Keyboardwifipasswordinput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER  ) {
      keyenter_event_handler( e );
}
if ( event_code == LV_EVENT_READY) {
      keyready_event_handler( e );
}
if ( event_code == LV_EVENT_CANCEL) {
      keycancel_event_hadnler( e );
}
}
void ui_event_Label31( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      scanwifilist_event_handler( e );
}
}
void ui_event_Switchpasswordmode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      switchnopasswordmode_event_handler( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      switchpasswordmode_event_handler( e );
}
}
void ui_event_Btnchangchangyingyu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnchangchangyingyu_event_handler( e );
}
}
void ui_event_Btnxiaozhupeiqi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnxiaozhupeiqi_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
}
}
void ui_event_Btntonghuagushi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btntonghuagushi_event_handler( e );
}
}
void ui_event_Btnzhishikepu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnzhishikepu_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
}
}
void ui_event_Btnguoxuetangshi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnguoxuetangshi_event_handler( e );
}
}
void ui_event_Btnsanzijing( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnsanzijing_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
}
}
void ui_event_Imageyuwenbaozang( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      Imageyuwenbaozangleft_event_handler( e );
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      Imageyuwenbaozangright_event_handler( e );
}
}
void ui_event_Btnjiafayunsuan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnjiafayunsuan_event_handler( e );
}
}
void ui_event_Btnjianfayunsuan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnjianfayunsuan_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
      Btnfanhuizhuye4_event_handler( e );
}
}
void ui_event_Btnchongxinchuti( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnchongxinchuti_event_handler( e );
}
}
void ui_event_Btnchakandaan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnchakandaan_event_handler( e );
}
}
void ui_event_Dropdownmaxnum( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      Dropdownmaxnum_event_handler( e );
}
}
void ui_event_Btnrenshizimu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnrenshizimu_event_handler( e );
}
}
void ui_event_Btnquweidanci( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      Btnquweidanci_event_handler( e );
}
}
void ui_event_Btnfanhuizhuye5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_welcomescreen_screen_init();
ui_mainscreen_screen_init();
ui_xitongshezhi_screen_init();
ui_quweidonghua_screen_init();
ui_zhinengai_screen_init();
ui_yuwenbaozang_screen_init();
ui_shuxueyunsuan_screen_init();
ui_yingyuqimeng_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_welcomescreen);
}
