// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_welcomescreen_screen_init(void)
{
ui_welcomescreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_welcomescreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_welcomescreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_welcomescreen);

ui_Bg7 = lv_img_create(ui_welcomescreen);
lv_img_set_src(ui_Bg7, &ui_img_fengmian_png);
lv_obj_set_width( ui_Bg7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Bg7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Bg7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Bg7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Bg7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_welcomescreen, ui_event_welcomescreen, LV_EVENT_ALL, NULL);

}
