// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_zhinengai_screen_init(void)
{
ui_zhinengai = lv_obj_create(NULL);
lv_obj_clear_flag( ui_zhinengai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bg3 = lv_img_create(ui_zhinengai);
lv_img_set_src(ui_Bg3, &ui_img_bg_img_png);
lv_obj_set_width( ui_Bg3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Bg3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Bg3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Bg3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Bg3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTitle3 = lv_label_create(ui_zhinengai);
lv_obj_set_width( ui_LabelTitle3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitle3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTitle3, 60 );
lv_obj_set_y( ui_LabelTitle3, -110 );
lv_obj_set_align( ui_LabelTitle3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTitle3,"智能AI");
lv_obj_set_style_text_color(ui_LabelTitle3, lv_color_hex(0x14FF2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTitle3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelTitle3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTitle3, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btntonghuagushi = lv_btn_create(ui_zhinengai);
lv_obj_set_width( ui_Btntonghuagushi, 100);
lv_obj_set_height( ui_Btntonghuagushi, 50);
lv_obj_set_x( ui_Btntonghuagushi, -170 );
lv_obj_set_y( ui_Btntonghuagushi, -50 );
lv_obj_set_align( ui_Btntonghuagushi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btntonghuagushi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btntonghuagushi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Btntonghuagushi, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Btntonghuagushi);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"童话故事");

ui_Btnzhishibaike = lv_btn_create(ui_zhinengai);
lv_obj_set_width( ui_Btnzhishibaike, 100);
lv_obj_set_height( ui_Btnzhishibaike, 50);
lv_obj_set_x( ui_Btnzhishibaike, -170 );
lv_obj_set_y( ui_Btnzhishibaike, 25 );
lv_obj_set_align( ui_Btnzhishibaike, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnzhishibaike, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnzhishibaike, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_Btnzhishibaike);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"知识百科");
lv_obj_set_style_text_font(ui_Label14, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btnfanhuizhuye2 = lv_btn_create(ui_zhinengai);
lv_obj_set_width( ui_Btnfanhuizhuye2, 100);
lv_obj_set_height( ui_Btnfanhuizhuye2, 50);
lv_obj_set_x( ui_Btnfanhuizhuye2, -170 );
lv_obj_set_y( ui_Btnfanhuizhuye2, 100 );
lv_obj_set_align( ui_Btnfanhuizhuye2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnfanhuizhuye2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnfanhuizhuye2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_Btnfanhuizhuye2);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"返回主页");
lv_obj_set_style_text_font(ui_Label15, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabViezhinengai = lv_tabview_create(ui_zhinengai, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViezhinengai, 300);
lv_obj_set_height( ui_TabViezhinengai, 200);
lv_obj_set_x( ui_TabViezhinengai, 60 );
lv_obj_set_y( ui_TabViezhinengai, 21 );
lv_obj_set_align( ui_TabViezhinengai, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViezhinengai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_Imagezhinengai = lv_img_create(ui_zhinengai);
lv_obj_set_width( ui_Imagezhinengai, 300);
lv_obj_set_height( ui_Imagezhinengai, 200);
lv_obj_set_x( ui_Imagezhinengai, 60 );
lv_obj_set_y( ui_Imagezhinengai, 21 );
lv_obj_set_align( ui_Imagezhinengai, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imagezhinengai, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imagezhinengai, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Btntonghuagushi, ui_event_Btntonghuagushi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnzhishibaike, ui_event_Btnzhishibaike, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnfanhuizhuye2, ui_event_Btnfanhuizhuye2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_zhinengai, ui_event_zhinengai, LV_EVENT_ALL, NULL);

}
