// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_shuxueyunsuan_screen_init(void)
{
ui_shuxueyunsuan = lv_obj_create(NULL);
lv_obj_clear_flag( ui_shuxueyunsuan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bg5 = lv_img_create(ui_shuxueyunsuan);
lv_img_set_src(ui_Bg5, &ui_img_bg_img_png);
lv_obj_set_width( ui_Bg5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Bg5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Bg5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Bg5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Bg5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelTitle5 = lv_label_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_LabelTitle5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTitle5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTitle5, 60 );
lv_obj_set_y( ui_LabelTitle5, -100 );
lv_obj_set_align( ui_LabelTitle5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTitle5,"数学运算");
lv_obj_set_style_text_color(ui_LabelTitle5, lv_color_hex(0x14FF2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTitle5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelTitle5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTitle5, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btnjiafayunsuan = lv_btn_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Btnjiafayunsuan, 100);
lv_obj_set_height( ui_Btnjiafayunsuan, 50);
lv_obj_set_x( ui_Btnjiafayunsuan, -170 );
lv_obj_set_y( ui_Btnjiafayunsuan, -50 );
lv_obj_set_align( ui_Btnjiafayunsuan, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnjiafayunsuan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnjiafayunsuan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Btnjiafayunsuan, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_Btnjiafayunsuan);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"加法运算");

ui_Btnjianfayunsuan = lv_btn_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Btnjianfayunsuan, 100);
lv_obj_set_height( ui_Btnjianfayunsuan, 50);
lv_obj_set_x( ui_Btnjianfayunsuan, -170 );
lv_obj_set_y( ui_Btnjianfayunsuan, 25 );
lv_obj_set_align( ui_Btnjianfayunsuan, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnjianfayunsuan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnjianfayunsuan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_Btnjianfayunsuan);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"减法运算");
lv_obj_set_style_text_font(ui_Label20, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btnfanhuizhuye4 = lv_btn_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Btnfanhuizhuye4, 100);
lv_obj_set_height( ui_Btnfanhuizhuye4, 50);
lv_obj_set_x( ui_Btnfanhuizhuye4, -170 );
lv_obj_set_y( ui_Btnfanhuizhuye4, 100 );
lv_obj_set_align( ui_Btnfanhuizhuye4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnfanhuizhuye4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnfanhuizhuye4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_Btnfanhuizhuye4);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"返回主页");
lv_obj_set_style_text_font(ui_Label21, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabViezhinengai2 = lv_tabview_create(ui_shuxueyunsuan, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabViezhinengai2, 302);
lv_obj_set_height( ui_TabViezhinengai2, 96);
lv_obj_set_x( ui_TabViezhinengai2, 67 );
lv_obj_set_y( ui_TabViezhinengai2, -13 );
lv_obj_set_align( ui_TabViezhinengai2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabViezhinengai2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags


ui_Btnchongxinchuti = lv_btn_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Btnchongxinchuti, 100);
lv_obj_set_height( ui_Btnchongxinchuti, 50);
lv_obj_set_x( ui_Btnchongxinchuti, -10 );
lv_obj_set_y( ui_Btnchongxinchuti, 100 );
lv_obj_set_align( ui_Btnchongxinchuti, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnchongxinchuti, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnchongxinchuti, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label25 = lv_label_create(ui_Btnchongxinchuti);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"重新出题");
lv_obj_set_style_text_font(ui_Label25, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Btnchakandaan = lv_btn_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Btnchakandaan, 100);
lv_obj_set_height( ui_Btnchakandaan, 50);
lv_obj_set_x( ui_Btnchakandaan, 145 );
lv_obj_set_y( ui_Btnchakandaan, 100 );
lv_obj_set_align( ui_Btnchakandaan, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Btnchakandaan, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Btnchakandaan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label26 = lv_label_create(ui_Btnchakandaan);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, -1 );
lv_obj_set_y( ui_Label26, -1 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"查看答案");
lv_obj_set_style_text_font(ui_Label26, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, 66 );
lv_obj_set_y( ui_Label27, -39 );
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"当前模式:      以内的加法");
lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x1F14F1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label27, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_shuxueyunsuan);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, 64 );
lv_obj_set_y( ui_Label28, 3 );
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"点击<重新出题>开始测试");
lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xE5D126), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label28, &ui_font_chnfont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdownmaxnum = lv_dropdown_create(ui_shuxueyunsuan);
lv_dropdown_set_options( ui_Dropdownmaxnum, "5\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n60\n65\n70\n75\n80\n85\n90\n95\n100" );
lv_obj_set_width( ui_Dropdownmaxnum, 65);
lv_obj_set_height( ui_Dropdownmaxnum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdownmaxnum, 59 );
lv_obj_set_y( ui_Dropdownmaxnum, -37 );
lv_obj_set_align( ui_Dropdownmaxnum, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdownmaxnum, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



lv_obj_add_event_cb(ui_Btnjiafayunsuan, ui_event_Btnjiafayunsuan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnjianfayunsuan, ui_event_Btnjianfayunsuan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnfanhuizhuye4, ui_event_Btnfanhuizhuye4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnchongxinchuti, ui_event_Btnchongxinchuti, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Btnchakandaan, ui_event_Btnchakandaan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Dropdownmaxnum, ui_event_Dropdownmaxnum, LV_EVENT_ALL, NULL);

}
