import os
import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
user_app_path = rtconfig.USER_APP_DIR
group = []

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

# add user app search
if os.path.exists(os.path.join(user_app_path, 'SConscript')):
	group = group + SConscript(os.path.join(user_app_path, 'SConscript'), 
        variant_dir=rtconfig.BUILD_OUT_DIR + '/user_app/', duplicate=0)

Return('group')
